#!/bin/bash
TTYSKIN='dark';
PTYSKIN='modarin256-defbg';
ROOTPTYSKIN='modarin256root-defbg';

if [[ -z `tty|awk -F/ '{print $3}'|grep tty` ]];then
  TERM=xterm-256color;
  USERSKIN=$PTYSKIN;
  ROOTSKIN=$ROOTPTYSKIN;

  if [[ $EUID == 0 ]]; then
    mc -S $ROOTSKIN $@
  else
    mc -S $USERSKIN $@
  fi

else
  TERM=linux;
  USERSKIN=$TTYSKIN;
  ROOTSKIN=$TTYSKIN;

  if [[ $EUID == 0 ]]; then
    mc -S $ROOTSKIN $@
  else
    mc -S $USERSKIN $@
  fi

fi
