#!/bin/bash
TTYSKIN='dark';
PTYSKIN='modarin256-defbg';
ROOTPTYSKIN='modarin256root-defbg';

function run_mc {
  if [[ $EUID == 0 ]]; then
    mc -S $ROOTSKIN;
  else
    mc -S $USERSKIN;
  fi
}

if [[ -z `tty|awk -F/ '{print $3}'|grep tty` ]];then
  TERM=xterm-256color;
  USERSKIN=$PTYSKIN;
  ROOTSKIN=$ROOTPTYSKIN;
  
  run_mc;
else 
  TERM=linux;
  USERSKIN=$TTYSKIN;
  ROOTSKIN=$TTYSKIN;

  run_mc;
fi


